color0 #1a1b1c
color1 #db6d6d
color2 #91ad83
color3 #d1b394
color4 #8faeb1
color5 #b892b1
color6 #8fb8a7
color7 #cdc5bd
color8 #3e4042
color9 #e58e8e
color10 #b0cc9d
color11 #e6ccb1
color12 #acc6c9
color13 #d1b1cc
color14 #acc9bc
color15 #e5dfd9

cursor                #cdc5bd
cursor_text_color     #1a1b1c
background            #1a1b1c
foreground            #cdc5bd
selection_foreground  #1a1b1c
selection_background  #db6d6d
active_border_color   #db6d6d
inactive_border_color #252627
url_color             #db6d6d

active_tab_foreground   #1a1b1c
active_tab_background   #db6d6d
inactive_tab_foreground #a69d96
inactive_tab_background #252627
cursor_trail_color      #a69d96
