# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x000000ff
rootcolor = 0x1a1b1cff
bordercolor = 0x656668ff
dropcolor = 0xdb6d6d80
splitcolor = 0x8faeb1ff
focuscolor = 0xdb6d6dff
maximizescreencolor = 0xd1b394ff
urgentcolor = 0xdb6d6dff
scratchpadcolor = 0x8faeb1ff
globalcolor = 0x831212ff
overlaycolor = 0x8a5a28ff
jump_label_decorate_fg_color = 0xcdc5bdff
jump_label_decorate_bg_color = 0x2f3031ff
jump_label_decorate_focus_fg_color = 0x1a1b1cff
jump_label_decorate_focus_bg_color = 0xdb6d6dff
jump_label_decorate_border_color = 0x656668ff
group_bar_decorate_fg_color = 0xcdc5bdff
group_bar_decorate_bg_color = 0x2f3031ff
group_bar_decorate_focus_fg_color = 0x1a1b1cff
group_bar_decorate_focus_bg_color = 0xdb6d6dff
group_bar_decorate_border_color = 0x656668ff
