unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix
unbind C-q
bind q kill-server
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
set -g status-left ""
set -g status-left "#{?client_prefix,#[bg=red]#[fg=white] : #[default], }"
